name: Test Site1234
favicon: null
layout_spectrum: 0.29058
typography_spectrum: 0.33258697600103915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.45805791416205466
  lightness: 0.7977075655944645
  saturation: 0.6385254191700369
  rhythmicContrast: 0.7221996539738029
purpose: []
